### ISSUE TITLE
ImportError: libmysqlclient.so.18: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by johanvdwerken** [google/crmint#136]
While executing the step-by-step deployment wiki I get the following errors in Cloud Shell. Note I replaced the project id with 'project-id'. When I go to https://project-id.appspot.com after deploying I get a message 'There is error after loading data.'

```
>>>> Deploy
---> Get current project identifier  
     Project ID found: project-id
---> Install required packages (1/3)  
---> Install required packages (2/3)  
---> Install required packages (3/3)  
     Working directory: /tmp/project-id
---> Copy source code to working directory (1/6)  
---> Copy source code to working directory (2/6)  
---> Copy source code to working directory (3/6)  
---> Copy source code to working directory (4/6)  
---> Copy source code to working directory (5/6)  
---> Copy source code to working directory (6/6)  
---> Install backends dependencies (1/6)  
---> Install backends dependencies (2/6)  
---> Install backends dependencies (3/6)  
---> Install backends dependencies (4/6)  
---> Install backends dependencies (5/6)  
---> Install backends dependencies (6/6)  
---> Deploy frontend service (1/3)  
---> Deploy frontend service (2/3)  
---> Deploy frontend service (3/3)  
---> Deploy backend services (1/4)  
---> Deploy backend services (2/4)  
---> Deploy backend services (3/4)  
---> Deploy backend services (4/4)  
---> Deploy the dispatch.yaml rules  
---> Start CloudSQL proxy (1/4)  
---> Start CloudSQL proxy (2/4)  
---> Start CloudSQL proxy (3/4)  
---> Start CloudSQL proxy (4/4)  
---> Configure Cloud SQL proxy settings  
---> Applying database migrations 


Applying database migrations: Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/project-id/backends/lib/flask/__main__.py", line 15, in <module>
    main(as_module=True)
  File "/tmp/project-id/backends/lib/flask/cli.py", line 513, in main
    cli.main(args=args, prog_name=name)
  File "/tmp/project-id/backends/lib/flask/cli.py", line 380, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/tmp/project-id/backends/lib/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/tmp/project-id/backends/lib/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/tmp/project-id/backends/lib/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/tmp/project-id/backends/lib/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tmp/project-id/backends/lib/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/tmp/project-id/backends/lib/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/tmp/project-id/backends/lib/flask/cli.py", line 256, in decorator
    with __ctx.ensure_object(ScriptInfo).load_app().app_context():
  File "/tmp/project-id/backends/lib/flask/cli.py", line 237, in load_app
    rv = locate_app(self.app_import_path)
  File "/tmp/project-id/backends/lib/flask/cli.py", line 90, in locate_app
    __import__(module)
  File "/tmp/project-id/backends/run_ibackend.py", line 28, in <module>
    app = create_app(api, config_object=CONFIG)
  File "/tmp/project-id/backends/ibackend/app.py", line 35, in create_app
    register_extensions(app)
  File "/tmp/project-id/backends/ibackend/app.py", line 45, in register_extensions
    init_engine(app.config['SQLALCHEMY_DATABASE_URI'])
  File "core/database.py", line 35, in init_engine
    engine = create_engine(uri, **kwargs)
  File "/tmp/project-id/backends/lib/sqlalchemy/engine/__init__.py", line 479, in create_engine
    return strategy.create(*args, **kwargs)
  File "/tmp/project-id/backends/lib/sqlalchemy/engine/strategies.py", line 87, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/tmp/project-id/backends/lib/sqlalchemy/dialects/mysql/mysqldb.py", line 118, in dbapi
    return __import__("MySQLdb")
  File "/tmp/project-id/backends/lib/MySQLdb/__init__.py", line 19, in <module>
    import _mysql
ImportError: libmysqlclient.so.18: cannot open shared object file: No such file or directory
 
Command: . env/bin/activate && python -m flask db upgrade

---> Sowing DB seeds  
Sowing DB seeds: Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/project-id/backends/lib/flask/__main__.py", line 15, in <module>
    main(as_module=True)
  File "/tmp/project-id/backends/lib/flask/cli.py", line 513, in main
    cli.main(args=args, prog_name=name)
  File "/tmp/project-id/backends/lib/flask/cli.py", line 380, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/tmp/project-id/backends/lib/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/tmp/project-id/backends/lib/click/core.py", line 1132, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/tmp/project-id/backends/lib/click/core.py", line 1171, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/tmp/project-id/backends/lib/flask/cli.py", line 351, in get_command
    rv = info.load_app().cli.get_command(ctx, name)
  File "/tmp/project-id/backends/lib/flask/cli.py", line 237, in load_app
    rv = locate_app(self.app_import_path)
  File "/tmp/project-id/backends/lib/flask/cli.py", line 90, in locate_app
    __import__(module)
  File "/tmp/project-id/backends/run_ibackend.py", line 28, in <module>
    app = create_app(api, config_object=CONFIG)
  File "/tmp/project-id/backends/ibackend/app.py", line 35, in create_app
    register_extensions(app)
  File "/tmp/project-id/backends/ibackend/app.py", line 45, in register_extensions
    init_engine(app.config['SQLALCHEMY_DATABASE_URI'])
  File "core/database.py", line 35, in init_engine
    engine = create_engine(uri, **kwargs)
  File "/tmp/project-id/backends/lib/sqlalchemy/engine/__init__.py", line 479, in create_engine
    return strategy.create(*args, **kwargs)
  File "/tmp/project-id/backends/lib/sqlalchemy/engine/strategies.py", line 87, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/tmp/project-id/backends/lib/sqlalchemy/dialects/mysql/mysqldb.py", line 118, in dbapi
    return __import__("MySQLdb")
  File "/tmp/project-id/backends/lib/MySQLdb/__init__.py", line 19, in <module>
    import _mysql
ImportError: libmysqlclient.so.18: cannot open shared object file: No such file or directory
 
Command: . env/bin/activate && python -m flask db-seeds
---> Stop CloudSQL proxy  
Done.
```

**Comment by chris32g** [comment]
Hello, any update on this issue?

**Comment by osuarez-div** [comment]
Hi, I am having the same issue after make a first deployment and then a re-deployment of the tool in the same project. I have deployed the tool in other projects (only one time) and never got this error.

**Comment by Slony** [comment]
Hey guys, thanks for reporting the issue. We're investigating it at the moment and will come back to you with the solution once we find it.

**Comment by Download** [comment]
We just created a new project with nothing in it yet and tried to deploy CRMInt and we run into exactly the same error. It seems installing CRMInt is not possible right now. When you open the web UI it tries to load the data and fails and then you cannot use CRMInt in any way.

**Comment by Slony** [comment]
The issue has been fixed with [PR#138](https://github.com/google/crmint/pull/138).

The problem was due to `MySQL-python` package using its own `_mysql.so` binary that refers to `libmysqlclient.so.18` which was replaced with `libmysqlclient.so.20` in Cloud Shell recently.

**Please, [update CRMint to the latest version](https://github.com/google/crmint/wiki/Update-CRMint-to-the-latest-version).**

Thank you @johanvdwerken, @chris32g, @osuarez-div, and @Download for reporting and confirming the issue. Can you confirm that the solution provided works for you?

**Comment by johanvdwerken** [comment]
I updated CRMint for an existing project and it completed without errors. Thanks @Slony!

**Comment by Slony** [comment]
@johanvdwerken thanks for confirmation! I'm closing the issue.

**Comment by osuarez-div** [comment]
I also updated the existing deployment of CRMint and it solved the issue! Thanks @Slony!

**Comment by Download** [comment]
Yes, solved it for us too
