### ISSUE TITLE
Tests and other scripts seem to be missing some dependencies

### ISSUE THREAD

**Issue by aymanfarhat** [google/crmint#17]
Trying to run the following commands for a local dev setup (MacOS) after navigating to backends directory, following the wiki guide. Output below:

`python runtests.py $GOOGLE_CLOUD_SDK`
```
Traceback (most recent call last):
  File "runtests.py", line 98, in <module>
    result = main(args.sdk_path, args.test_path, args.test_pattern)
  File "runtests.py", line 60, in main
    import dev_appserver
ImportError: No module named dev_appserver
```

`python run_ibackend.py`
```
Traceback (most recent call last):
  File "run_ibackend.py", line 16, in <module>
    import appengine_config
  File "/Users/ayman/projects/crmint/backends/appengine_config.py", line 20, in <module>
    from google.appengine.ext import vendor
ImportError: No module named google.appengine.ext
```

`python run_jbackend.py`
```
Traceback (most recent call last):
  File "run_jbackend.py", line 18, in <module>
    from jbackend.app import create_app
  File "/Users/ayman/projects/crmint/backends/jbackend/app.py", line 21, in <module>
    from core.database import init_engine
  File "/Users/ayman/projects/crmint/backends/core/database.py", line 15, in <module>
    from sqlalchemy import create_engine
ImportError: No module named sqlalchemy
```

All dependencies install in the virtualenv already.

**Comment by dulacp** [comment]
Hi @aymanfarhat,

Can you please share your config with `$ gcloud info`?
You might have a few sensitive infos to redact though.

Cheers
