### ISSUE TITLE
CRMint Deployment Not Working : tuple index out of range

### ISSUE THREAD

**Issue by PA-Mousset** [google/crmint#200]
I have one persisting error during the deployment phase of CRMint following carefully the[ starting guide](https://google.github.io/crmint/docs/quickstart/cloudshell.md). My first error was a SQL-related error. I was able to fix it from another issue closed on this repository. The error was: 
` (sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1045, "Access denied for user 'crmintapp'@'cloudsqlproxy~34.76.202.116' (using password: YES)")` 

I fixed it by changing the password of `crmintapp` user in my SQL instances directly in the GCP console and in my script as well (`crmint/cli/stages/atf-sbx-mousset2.py`). 

I still have the second error and the error log is not really helpful for me. This error appears after the first issue (the one I fixed). It seems it's an IndexError but I am super confused of the location of that index error and why it occurs. 

**Error log:**

```
---> Configure Cloud SQL proxy settings  
---> Applying database migrations  
---> Sowing DB seeds  
Sowing DB seeds: Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/atf-sbx-mousset2/backends/lib/flask/__main__.py", line 15, in <module>
    main(as_module=True)
  File "/tmp/atf-sbx-mousset2/backends/lib/flask/cli.py", line 513, in main
    cli.main(args=args, prog_name=name)
  File "/tmp/atf-sbx-mousset2/backends/lib/flask/cli.py", line 380, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/tmp/atf-sbx-mousset2/backends/lib/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/tmp/atf-sbx-mousset2/backends/lib/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/tmp/atf-sbx-mousset2/backends/lib/click/core.py", line 1066, in invoke
  File "/tmp/atf-sbx-mousset2/backends/lib/sqlalchemy/orm/query.py", line 197, in __init__
    self._set_entities(entities)
  File "/tmp/atf-sbx-mousset2/backends/lib/sqlalchemy/orm/query.py", line 225, in _set_entities
    self._set_entity_selectables(self._entities)
  File "/tmp/atf-sbx-mousset2/backends/lib/sqlalchemy/orm/query.py", line 256, in _set_entity_selectables
    ent.setup_entity(*d[entity])
  File "/tmp/atf-sbx-mousset2/backends/lib/sqlalchemy/orm/query.py", line 4324, in setup_entity
    self._with_polymorphic = ext_info.with_polymorphic_mappers
  File "/tmp/atf-sbx-mousset2/backends/lib/sqlalchemy/util/langhelpers.py", line 884, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/tmp/atf-sbx-mousset2/backends/lib/sqlalchemy/orm/mapper.py", line 2155, in _with_polymorphic_mappers
    configure_mappers()
  File "/tmp/atf-sbx-mousset2/backends/lib/sqlalchemy/orm/mapper.py", line 3299, in configure_mappers
    mapper._post_configure_properties()
  File "/tmp/atf-sbx-mousset2/backends/lib/sqlalchemy/orm/mapper.py", line 1965, in _post_configure_properties
    prop.init()
  File "/tmp/atf-sbx-mousset2/backends/lib/sqlalchemy/orm/interfaces.py", line 197, in init
    self.do_init()
  File "/tmp/atf-sbx-mousset2/backends/lib/sqlalchemy/orm/relationships.py", line 2076, in do_init
    self._process_dependent_arguments()
  File "/tmp/atf-sbx-mousset2/backends/lib/sqlalchemy/orm/relationships.py", line 2105, in _process_dependent_arguments
    setattr(self, attr, attr_value())
  File "/tmp/atf-sbx-mousset2/backends/lib/sqlalchemy/ext/declarative/clsregistry.py", line 326, in __call__
    x = eval(self.arg, globals(), self._dict)
  File "<string>", line 1, in <module>
  File "/tmp/atf-sbx-mousset2/backends/lib/sqlalchemy/ext/declarative/clsregistry.py", line 219, in __getattr__
    if key not in mp.all_orm_descriptors:
  File "/tmp/atf-sbx-mousset2/backends/lib/sqlalchemy/util/langhelpers.py", line 884, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/tmp/atf-sbx-mousset2/backends/lib/sqlalchemy/orm/mapper.py", line 2453, in all_orm_descriptors
    dict(self.class_manager._all_sqla_attributes())
  File "/tmp/atf-sbx-mousset2/backends/lib/sqlalchemy/orm/instrumentation.py", line 152, in _all_sqla_attributes
    inherits = supercls.__mro__[1]
IndexError: tuple index out of range
 
```

**Comment by hampussanden** [comment]
I'm having the exact same issue as you @PA-Mousset

**Comment by PA-Mousset** [comment]
> I'm having the exact same issue as you @PA-Mousset

https://stackoverflow.com/questions/64581834/crmint-deployment-issue-indexerror-tuple-index-out-of-range

**Comment by hampussanden** [comment]
Thank you @PA-Mousset! Worked like a charm.

**Comment by dulacp** [comment]
We are closing this issue since the new release of CRMint 2.0 should fix this issue, please see the details in the mentioned above.
