### ISSUE TITLE
Deploy CRMint in Google Cloud, Applying DB migrations / Sowing DB seeds

### ISSUE THREAD

**Issue by bmind** [google/crmint#50]
I'm using the docs from: https://github.com/google/crmint/wiki/Deploy-CRMint-on-Google-Cloud-Platform to deploy CRMint in Google Cloud (master branch). On the second command:

```git clone https://github.com/google/crmint.git
cd crmint
bin/app cloud setup
bin/app cloud deploy

.. at the end of deploy i've got some errors on this steps:
```

**==> Applying DB migrations**

``` 2018/10/22 17:32:28 Listening on /tmp/cloudsql/crmint-bmind3:europe-west1:crmintapp for crmint-bmind3:europe-west1:crmintapp
2018/10/22 17:32:28 Listening on /tmp/cloudsql/crmint-bmind3:europe-west1:crmintapp for crmint-bmind3:europe-west1:crmintapp
2018/10/22 17:32:28 Ready for new connections
2018/10/22 17:32:29 New connection for "crmint-bmind3:europe-west1:crmintapp"
Traceback (most recent call last):
2018/10/22 17:32:29 Client closed local connection on /tmp/cloudsql/crmint-bmind3:europe-west1:crmintapp
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/crmint-bmind3/backends/lib/flask/__main__.py", line 15, in <module>
    main(as_module=True)
  File "/tmp/crmint-bmind3/backends/lib/flask/cli.py", line 513, in main
    cli.main(args=args, prog_name=name)
  File "/tmp/crmint-bmind3/backends/lib/flask/cli.py", line 380, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/tmp/crmint-bmind3/backends/lib/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/tmp/crmint-bmind3/backends/lib/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/tmp/crmint-bmind3/backends/lib/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/tmp/crmint-bmind3/backends/lib/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tmp/crmint-bmind3/backends/lib/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/tmp/crmint-bmind3/backends/lib/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/tmp/crmint-bmind3/backends/lib/flask/cli.py", line 257, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/tmp/crmint-bmind3/backends/lib/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/tmp/crmint-bmind3/backends/lib/flask_migrate/cli.py", line 132, in upgrade
    _upgrade(directory, revision, sql, tag, x_arg)
  File "/tmp/crmint-bmind3/backends/lib/flask_migrate/__init__.py", line 244, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/tmp/crmint-bmind3/backends/lib/alembic/command.py", line 254, in upgrade
    script.run_env()
  File "/tmp/crmint-bmind3/backends/lib/alembic/script/base.py", line 427, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/tmp/crmint-bmind3/backends/lib/alembic/util/pyfiles.py", line 81, in load_python_file
    module = load_module_py(module_id, path)
  File "/tmp/crmint-bmind3/backends/lib/alembic/util/compat.py", line 135, in load_module_py
    mod = imp.load_source(module_id, path, fp)
 File "migrations/env.py", line 104, in <module>
    run_migrations_online()
  File "migrations/env.py", line 88, in run_migrations_online
    connection = engine.connect()
  File "/tmp/crmint-bmind3/backends/lib/sqlalchemy/engine/base.py", line 2102, in connect
    return self._connection_cls(self, **kwargs)
  File "/tmp/crmint-bmind3/backends/lib/sqlalchemy/engine/base.py", line 90, in __init__
    if connection is not None else engine.raw_connection()
  File "/tmp/crmint-bmind3/backends/lib/sqlalchemy/engine/base.py", line 2188, in raw_connection
    self.pool.unique_connection, _connection)
  File "/tmp/crmint-bmind3/backends/lib/sqlalchemy/engine/base.py", line 2162, in _wrap_pool_connect
    e, dialect, self)
  File "/tmp/crmint-bmind3/backends/lib/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception_noconnection
    exc_info
  File "/tmp/crmint-bmind3/backends/lib/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/tmp/crmint-bmind3/backends/lib/sqlalchemy/engine/base.py", line 2158, in _wrap_pool_connect
    return fn()
  File "/tmp/crmint-bmind3/backends/lib/sqlalchemy/pool.py", line 342, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/tmp/crmint-bmind3/backends/lib/sqlalchemy/pool.py", line 788, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/tmp/crmint-bmind3/backends/lib/sqlalchemy/pool.py", line 529, in checkout
    rec = pool._do_get()
  File "/tmp/crmint-bmind3/backends/lib/sqlalchemy/pool.py", line 1284, in _do_get
    return self._create_connection()
  File "/tmp/crmint-bmind3/backends/lib/sqlalchemy/pool.py", line 347, in _create_connection
    return _ConnectionRecord(self)
  File "/tmp/crmint-bmind3/backends/lib/sqlalchemy/pool.py", line 474, in __init__
    self.__connect(first_connect_check=True)
  File "/tmp/crmint-bmind3/backends/lib/sqlalchemy/pool.py", line 671, in __connect
    connection = pool._invoke_creator(self)
  File "/tmp/crmint-bmind3/backends/lib/sqlalchemy/engine/strategies.py", line 106, in connect
    return dialect.connect(*cargs, **cparams)
  File "/tmp/crmint-bmind3/backends/lib/sqlalchemy/engine/default.py", line 412, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/tmp/crmint-bmind3/backends/lib/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/tmp/crmint-bmind3/backends/lib/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1045, "Access denied for user 'crmintapp'@'cloudsqlproxy~35.205.214.149' (using password: YES)") (Background on this error at: http://sqlalche.me/e/e3q8)
```

**==> Sowing DB seeds**

``` 
2018/10/22 17:32:30 New connection for "crmint-bmind3:europe-west1:crmintapp"
Traceback (most recent call last):
2018/10/22 17:32:30 Client closed local connection on /tmp/cloudsql/crmint-bmind3:europe-west1:crmintapp
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/crmint-bmind3/backends/lib/flask/__main__.py", line 15, in <module>
    main(as_module=True)
  File "/tmp/crmint-bmind3/backends/lib/flask/cli.py", line 513, in main
    cli.main(args=args, prog_name=name)
  File "/tmp/crmint-bmind3/backends/lib/flask/cli.py", line 380, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/tmp/crmint-bmind3/backends/lib/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/tmp/crmint-bmind3/backends/lib/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/tmp/crmint-bmind3/backends/lib/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tmp/crmint-bmind3/backends/lib/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/tmp/crmint-bmind3/backends/lib/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/tmp/crmint-bmind3/backends/lib/flask/cli.py", line 257, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/tmp/crmint-bmind3/backends/lib/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/tmp/crmint-bmind3/backends/flask_tasks.py", line 25, in db_seeds
    database.load_fixtures(logger_func=click.echo)
  File "/tmp/crmint-bmind3/backends/core/database.py", line 60, in load_fixtures
    general_setting = models.GeneralSetting.where(name=setting).first()
  File "/tmp/crmint-bmind3/backends/lib/sqlalchemy/orm/query.py", line 2895, in first
    ret = list(self[0:1])
  File "/tmp/crmint-bmind3/backends/lib/sqlalchemy/orm/query.py", line 2687, in __getitem__
    return list(res)
  File "/tmp/crmint-bmind3/backends/lib/sqlalchemy/orm/query.py", line 2995, in __iter__
    return self._execute_and_instances(context)
  File "/tmp/crmint-bmind3/backends/lib/sqlalchemy/orm/query.py", line 3016, in _execute_and_instances
    close_with_result=True)
  File "/tmp/crmint-bmind3/backends/lib/sqlalchemy/orm/query.py", line 3025, in _get_bind_args
    **kw
  File "/tmp/crmint-bmind3/backends/lib/sqlalchemy/orm/query.py", line 3007, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/tmp/crmint-bmind3/backends/lib/sqlalchemy/orm/session.py", line 1035, in connection
    execution_options=execution_options)
  File "/tmp/crmint-bmind3/backends/lib/sqlalchemy/orm/session.py", line 1042, in _connection_for_bind
    conn = engine.contextual_connect(**kw)
  File "/tmp/crmint-bmind3/backends/lib/sqlalchemy/engine/base.py", line 2123, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/tmp/crmint-bmind3/backends/lib/sqlalchemy/engine/base.py", line 2162, in _wrap_pool_connect
    e, dialect, self)
  File "/tmp/crmint-bmind3/backends/lib/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception_noconnection
    exc_info
  File "/tmp/crmint-bmind3/backends/lib/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/tmp/crmint-bmind3/backends/lib/sqlalchemy/engine/base.py", line 2158, in _wrap_pool_connect
    return fn()
  File "/tmp/crmint-bmind3/backends/lib/sqlalchemy/pool.py", line 400, in connect
    return _ConnectionFairy._checkout(self)
  File "/tmp/crmint-bmind3/backends/lib/sqlalchemy/pool.py", line 788, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/tmp/crmint-bmind3/backends/lib/sqlalchemy/pool.py", line 529, in checkout
    rec = pool._do_get()
  File "/tmp/crmint-bmind3/backends/lib/sqlalchemy/pool.py", line 1193, in _do_get
    self._dec_overflow()
  File "/tmp/crmint-bmind3/backends/lib/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/tmp/crmint-bmind3/backends/lib/sqlalchemy/pool.py", line 1190, in _do_get
    return self._create_connection()
  File "/tmp/crmint-bmind3/backends/lib/sqlalchemy/pool.py", line 347, in _create_connection
    return _ConnectionRecord(self)
  File "/tmp/crmint-bmind3/backends/lib/sqlalchemy/pool.py", line 474, in __init__
    self.__connect(first_connect_check=True)
  File "/tmp/crmint-bmind3/backends/lib/sqlalchemy/pool.py", line 671, in __connect
    connection = pool._invoke_creator(self)
  File "/tmp/crmint-bmind3/backends/lib/sqlalchemy/engine/strategies.py", line 106, in connect
    return dialect.connect(*cargs, **cparams)
  File "/tmp/crmint-bmind3/backends/lib/sqlalchemy/engine/default.py", line 412, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/tmp/crmint-bmind3/backends/lib/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/tmp/crmint-bmind3/backends/lib/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1045, "Access denied for user 'crmintapp'@'cloudsqlproxy~35.205.214.149' (using password: YES)") (Background on this error at: http://sqlalche.me/e/e3q8)
```

once deployed in app engine, I see this:

![GitHub Logo](https://bmind.es/github/crmint_deploy_issue.png)

Any clue about this issue? Any tips on how to deploy crmint in app engine ?

Also, in Cloud Shell i've tried to reset the statuses of all jobs and pipelines:

``` bin/app cloud reset ```

==> **Reseting statuses of jobs and pipelines**.

```
2018/10/22 17:42:51 New connection for "crmint-bmind3:europe-west1:crmintapp"
Traceback (most recent call last):
2018/10/22 17:42:51 Client closed local connection on /tmp/cloudsql/crmint-bmind3:europe-west1:crmintapp
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/crmint-bmind3/backends/lib/flask/__main__.py", line 15, in <module>
    main(as_module=True)
  File "/tmp/crmint-bmind3/backends/lib/flask/cli.py", line 513, in main
    cli.main(args=args, prog_name=name)
  File "/tmp/crmint-bmind3/backends/lib/flask/cli.py", line 380, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/tmp/crmint-bmind3/backends/lib/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/tmp/crmint-bmind3/backends/lib/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/tmp/crmint-bmind3/backends/lib/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tmp/crmint-bmind3/backends/lib/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/tmp/crmint-bmind3/backends/lib/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/tmp/crmint-bmind3/backends/lib/flask/cli.py", line 257, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/tmp/crmint-bmind3/backends/lib/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/tmp/crmint-bmind3/backends/flask_tasks.py", line 30, in reset_pipelines
    for pipeline in Pipeline.all():
  File "/tmp/crmint-bmind3/backends/lib/sqlalchemy_mixins/activerecord.py", line 64, in all
    return cls.query.all()
  File "/tmp/crmint-bmind3/backends/lib/sqlalchemy/orm/query.py", line 2843, in all
    return list(self)
 File "/tmp/crmint-bmind3/backends/lib/sqlalchemy/orm/query.py", line 2995, in __iter__
    return self._execute_and_instances(context)
  File "/tmp/crmint-bmind3/backends/lib/sqlalchemy/orm/query.py", line 3016, in _execute_and_instances
    close_with_result=True)
  File "/tmp/crmint-bmind3/backends/lib/sqlalchemy/orm/query.py", line 3025, in _get_bind_args
    **kw
  File "/tmp/crmint-bmind3/backends/lib/sqlalchemy/orm/query.py", line 3007, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/tmp/crmint-bmind3/backends/lib/sqlalchemy/orm/session.py", line 1035, in connection
    execution_options=execution_options)
  File "/tmp/crmint-bmind3/backends/lib/sqlalchemy/orm/session.py", line 1042, in _connection_for_bind
    conn = engine.contextual_connect(**kw)
  File "/tmp/crmint-bmind3/backends/lib/sqlalchemy/engine/base.py", line 2123, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/tmp/crmint-bmind3/backends/lib/sqlalchemy/engine/base.py", line 2162, in _wrap_pool_connect
    e, dialect, self)
  File "/tmp/crmint-bmind3/backends/lib/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception_noconnection
    exc_info
  File "/tmp/crmint-bmind3/backends/lib/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/tmp/crmint-bmind3/backends/lib/sqlalchemy/engine/base.py", line 2158, in _wrap_pool_connect
    return fn()
  File "/tmp/crmint-bmind3/backends/lib/sqlalchemy/pool.py", line 400, in connect
    return _ConnectionFairy._checkout(self)
  File "/tmp/crmint-bmind3/backends/lib/sqlalchemy/pool.py", line 788, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/tmp/crmint-bmind3/backends/lib/sqlalchemy/pool.py", line 529, in checkout
    rec = pool._do_get()
  File "/tmp/crmint-bmind3/backends/lib/sqlalchemy/pool.py", line 1193, in _do_get
    self._dec_overflow()
  File "/tmp/crmint-bmind3/backends/lib/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/tmp/crmint-bmind3/backends/lib/sqlalchemy/pool.py", line 1190, in _do_get
    return self._create_connection()
  File "/tmp/crmint-bmind3/backends/lib/sqlalchemy/pool.py", line 347, in _create_connection
    return _ConnectionRecord(self)
  File "/tmp/crmint-bmind3/backends/lib/sqlalchemy/pool.py", line 474, in __init__
    self.__connect(first_connect_check=True)
  File "/tmp/crmint-bmind3/backends/lib/sqlalchemy/pool.py", line 671, in __connect
    connection = pool._invoke_creator(self)
  File "/tmp/crmint-bmind3/backends/lib/sqlalchemy/engine/strategies.py", line 106, in connect
    return dialect.connect(*cargs, **cparams)
  File "/tmp/crmint-bmind3/backends/lib/sqlalchemy/engine/default.py", line 412, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/tmp/crmint-bmind3/backends/lib/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/tmp/crmint-bmind3/backends/lib/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1045, "Access denied for user 'crmintapp'@'cloudsqlproxy~35.205.214.149' (using password: YES)") (Background on this error at: http://sqlalche.me/e/e3q8)
```

 

Thank you

**Comment by davidjbutt** [comment]
One of the other threads had the following which should fix the issue:

I've double checked, and in SQL Cloud instance the user "crmintapp" is missing. Anyway, manually I created the user for mysql with all credentials from /script/variables/stages/<my_project_id>.sh and job done.

as a fix, in script/cloud/setup.sh this line:

   gcloud sql users create $db_username % --instance $db_instance_name \
	    --password $db_password --project $project_id_gae --quiet

should be replaced by:

gcloud sql users create $db_username --host % --instance $db_instance_name \
	    --password $db_password --project $project_id_gae --quiet

**Comment by Slony** [comment]
Thank you @davidjbutt for providing a solution! The bug is [fixed now](https://github.com/google/crmint/commit/1a58e1e49a1b0b4bd8dc6f752a6dbb459dffbd45).
